### PR TITLE
Try not to show infinite error dialogs

### PR DESCRIPTION
**Pull request by pde**
This is a start on resolving #210, but probably not ready yet.

### CODE REVIEW

**Comment by pde** [comment]
At one point I saw a segfault when disconnecting an iphone with this branch:
```
./droidcam
Video: /dev/video0
Audio: hw:1,1,0

(droidcam:1741809): Gdk-CRITICAL **: 11:04:52.824: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Segmentation fault
```
unsure of likely causes and out of time to debug for now!

**Comment by aramg** [comment]
Are you able to reproduce the segfault reliably, and get a gdb backtrace? Would need that to look into it.

As for the dialog spam, I've pushed some changes https://github.com/dev47apps/droidcam/tree/dev. 
Will test and update the client next week, as time permits (unable to at the moment)

**Comment by pde** [comment]
I wasn't immediately able to reproduce at all; will try running this version as my actual camera for a while and see what happens...

**Comment by pde** [comment]
@aramg your approach in the `dev` branch of turning off all the errors seems a bit aggressive in response to the spam problem? To me it seems to depend on whether there's a chance all those different errors ever help the user figure out why things aren't working (I'm sure you have some experience with that ;). If they do, you could consider either having one error dialog display and then that's enough (as I tried in this PR), or moving the errors to console output or a log UI pane, so people can dig in there if they need to.

**Comment by aramg** [comment]
The errors aren't being turned off? They've been moved out into the main app code (droidcam/-cli).
The underlying code shouldn't be interfering with the UI.

**Comment by aramg** [comment]
@pde the dev branch is updated with what should fix the spam if you yank the cable. 
Errors should still be displayed if the initial connection fails.

**Comment by aramg** [comment]
v1.8.2 released here on github

**Pull request closed without merging**
