### PR TITLE
Added vertical flip and 180° rotation

### PR DESCRIPTION
**Pull request by marcodotsh**
I don't know how good my code could be, but i needed to rotate by 180° my webcam because I only have Linux and i can't change my phone position, and to attend my classes at high school a camera is needed. To achieve this I used [TurboJPEG TJXOP](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/1.5.x/doc/html/group___turbo_j_p_e_g.html#ga2de531af4e7e6c4f124908376b354866), that was previously used only for horizontal flip.

### CODE REVIEW

**Comment by aramg** [comment]
Thanks for the PR. The code looks fine.
Feedback:
* whats the difference between vertical flip and the rot 180º ?
* it should be possible to combine horizontal and vertical flips, it looks like they cancel each other out in this form.
* lets not re-map the "M" shortcut unexpectedly like that.

**Comment by marcodotsh** [comment]
- Vertical flip mirrors the image vertically, rot 180° rotates the image, the rotation have (in theory) the same effect of applying both horizontal and vertical flip.
- I tried to maintain only horizontal and vertical flip because the rotation option maybe could be achieved with the combination of these two, but trying it I saw it acts weirdly when i try to apply two different transform operations, so I used rot 180 and I made sure only one at a time was active.
- Okay, I will revert it back to original.

**Comment by aramg** [comment]
OK, it would be really cool if the logic would automatically apply rot 180º when both flips are enabled, and the individual flips otherwise. To the user, it will them be seamless. Should not be hard to add that behaviour.

**Comment by marcodotsh** [comment]
I will try to do this. Thanks for the advice.

**Comment by marcodotsh** [comment]
I tried different approaches but I can't find a way that does not use too many if else statements, making the code difficult to read.

**Comment by Davilink** [comment]
any status ?

**Comment by marcodotsh** [comment]
@Davilink I managed to get both flips and rotation working with different computers and smartphones without issues, but when you apply a transformation on top of the other you get only the last one. I tried to make vflip and hflip work together but without success.
I will show my webcam setup in action:
- Normal:
Normal
- Horizontal flip ("m" in droidcam-cli):
Horizontal flip
- Vertical flip ("v" in droidcam-cli):
Vertical flip
- 180° rotation ("r" in droidcam-cli):
180° rotation

**Comment by logerom** [comment]
Is it possible to get an 90 degree rotation?
I want to have my front camera in portrait mode.

**Comment by aramg** [comment]
> Is it possible to get an 90 degree rotation?
> I want to have my front camera in portrait mode.

You can get portrait by inverting the webcam size. See the "HD Mode" section on [the app page](https://www.dev47apps.com/droidcam/linux/)

Will look at this PR as part of the next Linux update.
No ETA unfortunately, trying to finish a few other updates atm.

**Comment by aramg** [comment]
Added in 1323e5a7a55ad861fd6c7bb9bda3c40f740be38d

**Pull request closed without merging**
